import { SearchPage } from "../pages/SearchPage"
const searchPage = new SearchPage()

describe('Promotional Codes', () => {
  const data = require('../fixtures/search_data.json')

  it('To verify the result of search with promotional code when a valid format of code is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF3-FJK-418')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF3-FJK-418 used: 30% discount!')
  })

  it('To verify the result of search with promotional code when an invalid format of code is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('TEST')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Sorry, code TEST is not valid')
  })

  it('To verify the result of search with promotional code when there are seats available', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF3-FJK-418')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Seats available!')
      .should('contain', 'Promotional code AF3-FJK-418 used: 30% discount!')
      .should('contain', 'Call now on 0800 MARSAIR to book!')
  })

  it('To verify the result of search with promotional code when there are no seats available', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_year)
    searchPage.enterPromotionalCode('AF3-FJK-418')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Sorry, there are no more seats available.')
  })

  it('To verify the result of search with promotional code when characters are replaced by digits', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('993-999-418')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Sorry, code 993-999-418 is not valid')
  })

  it('To verify the result of search with promotional code when a valid code with 10% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF1-FJK-416')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF1-FJK-416 used: 10% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 20% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF2-FJK-417')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF2-FJK-417 used: 20% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 30% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF3-FJK-418')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF3-FJK-418 used: 30% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 40% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF4-FJK-419')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF4-FJK-419 used: 40% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 50% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF5-FJK-319')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF5-FJK-319 used: 50% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 60% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF6-FJK-219')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF6-FJK-219 used: 60% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 70% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF7-FJK-119')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF7-FJK-119 used: 70% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 80% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF8-FJK-019')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF8-FJK-019 used: 80% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 90% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF9-FJK-009')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF9-FJK-009 used: 90% discount!')
  })

  it('To verify the result of search with promotional code when a valid code with 00% discount is entered', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF0-FJK-415')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF0-FJK-415 used: 00% discount!')
  })

  it('To verify the result of search with promotional code when the first digit is replaced by characters', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AFA-FJK-415')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Sorry, code AFA-FJK-415 is not valid')
  })

  it('To verify the result of search with promotional code when the next 2 digits are replaced by characters', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF3-FJK-AA3')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Sorry, code AF3-FJK-AA3 is not valid')
  })

  it('To verify the result of search with promotional code when the sum of 3 digits is less than 10', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF3-FJK-418')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF3-FJK-418 used: 30% discount!')
  })

  it('To verify the result of search with promotional code when the sum of 3 digits is equal to 10', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('JJ5-OPQ-320')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code JJ5-OPQ-320 used: 50% discount!')
  })

  it('To verify the result of search with promotional code when the sum of 3 digits is more than 10', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('AF9-FJK-997')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Promotional code AF9-FJK-997 used: 90% discount!')
  })

  it('To verify the result of search with promotional code when the check digit is replaced by characters', () => {
    searchPage.navigateToSearchPage()
    searchPage.selectDeparture(data.jul)
    searchPage.selectReturn(data.dec_next_two_years)
    searchPage.enterPromotionalCode('JJ5-OPQ-32A')
    searchPage.clickSearch()
    cy.get('#content')
      .should('contain', 'Search Results')
      .should('contain', 'Sorry, code JJ5-OPQ-32A is not valid')
  })
})